# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis.ui'
#
# Created: Thu Nov 03 17:52:44 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Analysis(object):
    def setupUi(self, Analysis):
        Analysis.setObjectName("Analysis")
        Analysis.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Analysis.sizePolicy().hasHeightForWidth())
        Analysis.setSizePolicy(sizePolicy)
        Analysis.setMinimumSize(QtCore.QSize(800, 600))
        Analysis.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(Analysis)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(671, 180, 101, 51))
        self.startButton.setObjectName("startButton")
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(671, 250, 101, 51))
        self.stopButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stopButton.setObjectName("stopButton")
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(31, 170, 471, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.loopNum = QtGui.QSpinBox(self.centralwidget)
        self.loopNum.setGeometry(QtCore.QRect(670, 330, 46, 22))
        self.loopNum.setObjectName("loopNum")
        self.timePerLoop = QtGui.QSpinBox(self.centralwidget)
        self.timePerLoop.setGeometry(QtCore.QRect(670, 370, 46, 22))
        self.timePerLoop.setObjectName("timePerLoop")
        self.filePickerButton2 = QtGui.QPushButton(self.centralwidget)
        self.filePickerButton2.setEnabled(False)
        self.filePickerButton2.setGeometry(QtCore.QRect(451, 130, 51, 31))
        self.filePickerButton2.setObjectName("filePickerButton2")
        self.basePath = QtGui.QLineEdit(self.centralwidget)
        self.basePath.setEnabled(False)
        self.basePath.setGeometry(QtCore.QRect(31, 130, 411, 31))
        self.basePath.setObjectName("basePath")
        self.filePickerButton = QtGui.QPushButton(self.centralwidget)
        self.filePickerButton.setGeometry(QtCore.QRect(451, 80, 51, 31))
        self.filePickerButton.setObjectName("filePickerButton")
        self.roverPath = QtGui.QLineEdit(self.centralwidget)
        self.roverPath.setGeometry(QtCore.QRect(31, 80, 411, 31))
        self.roverPath.setObjectName("roverPath")
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(31, 60, 141, 18))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(31, 110, 141, 18))
        self.checkBox_2.setObjectName("checkBox_2")
        self.resolveAllButton = QtGui.QPushButton(self.centralwidget)
        self.resolveAllButton.setGeometry(QtCore.QRect(670, 60, 101, 51))
        self.resolveAllButton.setObjectName("resolveAllButton")
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 350, 471, 231))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 210, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.sameAsInput = QtGui.QCheckBox(self.centralwidget)
        self.sameAsInput.setEnabled(True)
        self.sameAsInput.setGeometry(QtCore.QRect(130, 240, 141, 18))
        self.sameAsInput.setChecked(True)
        self.sameAsInput.setObjectName("sameAsInput")
        self.outputPath = QtGui.QLineEdit(self.centralwidget)
        self.outputPath.setEnabled(False)
        self.outputPath.setGeometry(QtCore.QRect(30, 260, 411, 31))
        self.outputPath.setObjectName("outputPath")
        self.filePickerButton3 = QtGui.QPushButton(self.centralwidget)
        self.filePickerButton3.setEnabled(False)
        self.filePickerButton3.setGeometry(QtCore.QRect(450, 260, 51, 31))
        self.filePickerButton3.setObjectName("filePickerButton3")
        self.obsCheck = QtGui.QCheckBox(self.centralwidget)
        self.obsCheck.setGeometry(QtCore.QRect(30, 300, 73, 18))
        self.obsCheck.setChecked(True)
        self.obsCheck.setObjectName("obsCheck")
        self.navCheck = QtGui.QCheckBox(self.centralwidget)
        self.navCheck.setGeometry(QtCore.QRect(90, 300, 73, 18))
        self.navCheck.setChecked(True)
        self.navCheck.setObjectName("navCheck")
        self.staCheck = QtGui.QCheckBox(self.centralwidget)
        self.staCheck.setGeometry(QtCore.QRect(150, 300, 101, 18))
        self.staCheck.setChecked(True)
        self.staCheck.setObjectName("staCheck")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 240, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 330, 54, 12))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.reportCheck = QtGui.QCheckBox(self.centralwidget)
        self.reportCheck.setGeometry(QtCore.QRect(270, 300, 73, 18))
        self.reportCheck.setObjectName("reportCheck")
        Analysis.setCentralWidget(self.centralwidget)

        self.retranslateUi(Analysis)
        QtCore.QMetaObject.connectSlotsByName(Analysis)

    def retranslateUi(self, Analysis):
        Analysis.setWindowTitle(QtGui.QApplication.translate("Analysis", "Raw Measurement Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("Analysis", "start analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("Analysis", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.filePickerButton2.setText(QtGui.QApplication.translate("Analysis", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.filePickerButton.setText(QtGui.QApplication.translate("Analysis", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Analysis", "Rover Raw/RTCM file:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("Analysis", "Base  Raw/RTCM file:", None, QtGui.QApplication.UnicodeUTF8))
        self.resolveAllButton.setText(QtGui.QApplication.translate("Analysis", "analysis all", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Analysis", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Analysis", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.sameAsInput.setText(QtGui.QApplication.translate("Analysis", "Same as Input", None, QtGui.QApplication.UnicodeUTF8))
        self.filePickerButton3.setText(QtGui.QApplication.translate("Analysis", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.obsCheck.setText(QtGui.QApplication.translate("Analysis", "obs", None, QtGui.QApplication.UnicodeUTF8))
        self.navCheck.setText(QtGui.QApplication.translate("Analysis", "nav", None, QtGui.QApplication.UnicodeUTF8))
        self.staCheck.setText(QtGui.QApplication.translate("Analysis", "station info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Analysis", "Output Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Analysis", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.reportCheck.setText(QtGui.QApplication.translate("Analysis", "statistics", None, QtGui.QApplication.UnicodeUTF8))

